### ISSUE TITLE
Вопрос на засыпку

### ISSUE THREAD

**Issue by nikitas244** [n00rd1/FoodOption_TG-bot#1]
Допустим, я тренер и мне нужно отслеживать данные активности от моих подчинённых, данный бот подойдёт для этого? Я могу отслеживать сколько мои ученики потребляют каллории?

**Comment by n00rd1** [comment]
Бот предназначен, для автоматизации в работе с подбором питания. Помогает подобрать БЖУ (белки, жиры, углеводы) для клиентов с индивидуальным планом питания, либо выбрать готовый вариант для тех, кто смотрит общий формат. 

Если нужен иной функционал, то напишите мне по контактам в профиле, обсудим.
